/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Rangoda
 */
public class AddStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public AddStudent() {
        initComponents();
        
        setSize(576,610);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fName = new javax.swing.JLabel();
        txtfName = new javax.swing.JTextField();
        lName = new javax.swing.JLabel();
        txtlName = new javax.swing.JTextField();
        dob = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        combo_faculty = new javax.swing.JComboBox<>();
        combo_type = new javax.swing.JComboBox<>();
        combo_intake = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txttelNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Personal & Course Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 20, 233, 22);

        fName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fName.setForeground(new java.awt.Color(255, 255, 255));
        fName.setText("First Name");
        jPanel1.add(fName);
        fName.setBounds(110, 90, 90, 17);

        txtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtfName);
        txtfName.setBounds(300, 90, 120, 20);

        lName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lName.setForeground(new java.awt.Color(255, 255, 255));
        lName.setText("Last Name");
        jPanel1.add(lName);
        lName.setBounds(110, 130, 80, 17);

        txtlName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtlName);
        txtlName.setBounds(300, 130, 121, 20);

        dob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dob.setForeground(new java.awt.Color(255, 255, 255));
        dob.setText("DOB");
        jPanel1.add(dob);
        dob.setBounds(110, 170, 31, 17);

        txtdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdobActionPerformed(evt);
            }
        });
        jPanel1.add(txtdob);
        txtdob.setBounds(300, 170, 121, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Address");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 210, 56, 17);

        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtaddress);
        txtaddress.setBounds(300, 210, 121, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tel No.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 250, 48, 17);

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail);
        txtemail.setBounds(300, 300, 121, 20);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1002, 1480, 65, 23);

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1100, 1480, 55, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 300, 36, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Faculty");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(110, 340, 49, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Course type");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(110, 410, 100, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Intake");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(110, 460, 46, 17);

        combo_faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computing", "Business", "Engineering" }));
        jPanel1.add(combo_faculty);
        combo_faculty.setBounds(300, 340, 100, 20);

        combo_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bsc", "Msc" }));
        jPanel1.add(combo_type);
        combo_type.setBounds(300, 410, 60, 20);

        combo_intake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feb", "July" }));
        jPanel1.add(combo_intake);
        combo_intake.setBounds(300, 460, 60, 20);

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(340, 540, 80, 23);

        jButton4.setText("Next");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(460, 540, 60, 23);

        txttelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelNoActionPerformed(evt);
            }
        });
        jPanel1.add(txttelNo);
        txttelNo.setBounds(300, 250, 121, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsbm/images/background11.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 580, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            conn=MySqlConnect.ConnectDB();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        String value1=combo_type.getSelectedItem().toString();
        String value2=combo_intake.getSelectedItem().toString();
        String fac=combo_faculty.getSelectedItem().toString();

        //new CBacFebPreEducation(fac);

        if(fac=="Computing")
        {
            if(value1=="Bsc")
            {
                String Sql="INSERT INTO c_bac_student (fName,lName,dob,address,telNo,email,intake) values (?,?,?,?,?,?,?)";
                try{
                    pst=conn.prepareStatement(Sql);
                    pst.setString(1,txtfName.getText());
                    pst.setString(2,txtlName.getText());
                    pst.setString(3,txtdob.getText());
                    pst.setString(4,txtaddress.getText());
                    pst.setString(5,txtemail.getText());
                    pst.setString(6,txtemail.getText());

                    pst.setString(7,value2);

                    pst.executeUpdate();
                    //if(rs.next()){
                        if(value2=="Feb"){
                            CBacFebPreEducation cbfpe=new CBacFebPreEducation(fac);
                            cbfpe.setVisible(true);
                        }
                        else if(value2=="July"){
                            CBacJulyPreEducation cbjpe=new CBacJulyPreEducation(fac);
                            cbjpe.setVisible(true);
                        }

                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }

                else if(value1=="Msc")
                {
                    String Sql="INSERT INTO c_mas_student (fName,lName,dob,address,telNo,email,intake) values (?,?,?,?,?,?,?)";
                    try{
                        pst=conn.prepareStatement(Sql);
                        pst.setString(1,txtfName.getText());
                        pst.setString(2,txtlName.getText());
                        pst.setString(3,txtdob.getText());
                        pst.setString(4,txtaddress.getText());
                        pst.setString(5,txtemail.getText());
                        pst.setString(6,txtemail.getText());

                        pst.setString(7,value2);

                        pst.executeUpdate();
                        //if(rs.next()){

                            if(value2=="Feb"){
                                CMasFebPreEducation cmfpe=new CMasFebPreEducation(fac);
                                cmfpe.setVisible(true);
                            }
                            else if(value2=="July"){
                                CMasJulyPreEducation cmjpe=new CMasJulyPreEducation(fac);
                                cmjpe.setVisible(true);
                            }
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }
                }
                else if(fac=="Business")
                {
                    if(value1=="Bsc")
                    {
                        String Sql="INSERT INTO b_bac_student (fName,lName,dob,address,telNo,email,intake) values (?,?,?,?,?,?,?)";
                        try{
                            pst=conn.prepareStatement(Sql);
                            pst.setString(1,txtfName.getText());
                            pst.setString(2,txtlName.getText());
                            pst.setString(3,txtdob.getText());
                            pst.setString(4,txtaddress.getText());
                            pst.setString(5,txtemail.getText());
                            pst.setString(6,txtemail.getText());

                            pst.setString(7,value2);

                            pst.executeUpdate();
                            //if(rs.next()){
                                if(value2=="Feb"){
                                    CBacFebPreEducation cbfpe=new CBacFebPreEducation(fac);
                                    cbfpe.setVisible(true);
                                }
                                else if(value2=="July"){
                                    CBacJulyPreEducation cbjpe=new CBacJulyPreEducation(fac);
                                    cbjpe.setVisible(true);
                                }

                            }catch(Exception e){
                                JOptionPane.showMessageDialog(null, e);
                            }
                        }

                        else if(value1=="Msc")
                        {
                            String Sql="INSERT INTO b_mas_student (fName,lName,dob,address,telNo,email,intake) values (?,?,?,?,?,?,?)";
                            try{
                                pst=conn.prepareStatement(Sql);
                                pst.setString(1,txtfName.getText());
                                pst.setString(2,txtlName.getText());
                                pst.setString(3,txtdob.getText());
                                pst.setString(4,txtaddress.getText());
                                pst.setString(5,txtemail.getText());
                                pst.setString(6,txtemail.getText());

                                pst.setString(7,value2);

                                pst.executeUpdate();
                                //if(rs.next()){

                                    if(value2=="Feb"){
                                        CMasFebPreEducation cmfpe=new CMasFebPreEducation(fac);
                                        cmfpe.setVisible(true);
                                    }
                                    else if(value2=="July"){
                                        CMasJulyPreEducation cmjpe=new CMasJulyPreEducation(fac);
                                        cmjpe.setVisible(true);
                                    }
                                }catch(Exception e){
                                    JOptionPane.showMessageDialog(null, e);
                                }
                            }
                        }
                        else if(fac=="Engineering")
                        {
                            if(value1=="Bsc")
                            {
                                String Sql="INSERT INTO e_bac_student (fName,lName,dob,address,telNo,email,intake) values (?,?,?,?,?,?,?)";
                                try{
                                    pst=conn.prepareStatement(Sql);
                                    pst.setString(1,txtfName.getText());
                                    pst.setString(2,txtlName.getText());
                                    pst.setString(3,txtdob.getText());
                                    pst.setString(4,txtaddress.getText());
                                    pst.setString(5,txtemail.getText());
                                    pst.setString(6,txtemail.getText());

                                    pst.setString(7,value2);

                                    pst.executeUpdate();
                                    //if(rs.next()){
                                        if(value2=="Feb"){
                                            CBacFebPreEducation cbfpe=new CBacFebPreEducation(fac);
                                            cbfpe.setVisible(true);
                                        }
                                        else if(value2=="July"){
                                            CBacJulyPreEducation cbjpe=new CBacJulyPreEducation(fac);
                                            cbjpe.setVisible(true);
                                        }

                                    }catch(Exception e){
                                        JOptionPane.showMessageDialog(null, e);
                                    }
                                }

                                else if(value1=="Msc")
                                {
                                    String Sql="INSERT INTO e_mas_student (fName,lName,dob,address,telNo,email,intake) values (?,?,?,?,?,?,?)";
                                    try{
                                        pst=conn.prepareStatement(Sql);
                                        pst.setString(1,txtfName.getText());
                                        pst.setString(2,txtlName.getText());
                                        pst.setString(3,txtdob.getText());
                                        pst.setString(4,txtaddress.getText());
                                        pst.setString(5,txtemail.getText());
                                        pst.setString(6,txtemail.getText());

                                        pst.setString(7,value2);

                                        pst.executeUpdate();
                                        //if(rs.next()){

                                            if(value2=="Feb"){
                                                CMasFebPreEducation cmfpe=new CMasFebPreEducation(fac);
                                                cmfpe.setVisible(true);
                                            }
                                            else if(value2=="July"){
                                                CMasJulyPreEducation cmjpe=new CMasJulyPreEducation(fac);
                                                cmjpe.setVisible(true);
                                            }
                                        }catch(Exception e){
                                            JOptionPane.showMessageDialog(null, e);
                                        }
                                    }
                                }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CHome h=new CHome();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            conn=MySqlConnect.ConnectDB();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        String value1=combo_type.getSelectedItem().toString();
        String value2=combo_intake.getSelectedItem().toString();
        String fac=combo_faculty.getSelectedItem().toString();

        //new CBacFebPreEducation(fac);

        if(fac=="Computing")
        {
            if(value1=="Bsc")
            {
                String Sql="INSERT INTO c_bac_student (fName,lName,dob,address,telNo,email,intake) values (?,?,?,?,?,?,?)";
                try{
                    pst=conn.prepareStatement(Sql);
                    pst.setString(1,txtfName.getText());
                    pst.setString(2,txtlName.getText());
                    pst.setString(3,txtdob.getText());
                    pst.setString(4,txtaddress.getText());
                    pst.setString(5,txtemail.getText());
                    pst.setString(6,txtemail.getText());

                    pst.setString(7,value2);

                    pst.executeUpdate();
                    //if(rs.next()){
                        if(value2=="Feb"){
                            CBacFebPreEducation cbfpe=new CBacFebPreEducation(fac);
                            cbfpe.setVisible(true);
                        }
                        else if(value2=="July"){
                            CBacJulyPreEducation cbjpe=new CBacJulyPreEducation(fac);
                            cbjpe.setVisible(true);
                        }

                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }

                else if(value1=="Msc")
                {
                    String Sql="INSERT INTO c_mas_student (fName,lName,dob,address,telNo,email,intake) values (?,?,?,?,?,?,?)";
                    try{
                        pst=conn.prepareStatement(Sql);
                        pst.setString(1,txtfName.getText());
                        pst.setString(2,txtlName.getText());
                        pst.setString(3,txtdob.getText());
                        pst.setString(4,txtaddress.getText());
                        pst.setString(5,txtemail.getText());
                        pst.setString(6,txtemail.getText());

                        pst.setString(7,value2);

                        pst.executeUpdate();
                        //if(rs.next()){

                            if(value2=="Feb"){
                                CMasFebPreEducation cmfpe=new CMasFebPreEducation(fac);
                                cmfpe.setVisible(true);
                            }
                            else if(value2=="July"){
                                CMasJulyPreEducation cmjpe=new CMasJulyPreEducation(fac);
                                cmjpe.setVisible(true);
                            }
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }
                }
                else if(fac=="Business")
                {
                    if(value1=="Bsc")
                    {
                        String Sql="INSERT INTO b_bac_student (fName,lName,dob,address,telNo,email,intake) values (?,?,?,?,?,?,?)";
                        try{
                            pst=conn.prepareStatement(Sql);
                            pst.setString(1,txtfName.getText());
                            pst.setString(2,txtlName.getText());
                            pst.setString(3,txtdob.getText());
                            pst.setString(4,txtaddress.getText());
                            pst.setString(5,txtemail.getText());
                            pst.setString(6,txtemail.getText());

                            pst.setString(7,value2);

                            pst.executeUpdate();
                            //if(rs.next()){
                                if(value2=="Feb"){
                                    CBacFebPreEducation cbfpe=new CBacFebPreEducation(fac);
                                    cbfpe.setVisible(true);
                                }
                                else if(value2=="July"){
                                    CBacJulyPreEducation cbjpe=new CBacJulyPreEducation(fac);
                                    cbjpe.setVisible(true);
                                }

                            }catch(Exception e){
                                JOptionPane.showMessageDialog(null, e);
                            }
                        }

                        else if(value1=="Msc")
                        {
                            String Sql="INSERT INTO b_mas_student (fName,lName,dob,address,telNo,email,intake) values (?,?,?,?,?,?,?)";
                            try{
                                pst=conn.prepareStatement(Sql);
                                pst.setString(1,txtfName.getText());
                                pst.setString(2,txtlName.getText());
                                pst.setString(3,txtdob.getText());
                                pst.setString(4,txtaddress.getText());
                                pst.setString(5,txtemail.getText());
                                pst.setString(6,txtemail.getText());

                                pst.setString(7,value2);

                                pst.executeUpdate();
                                //if(rs.next()){

                                    if(value2=="Feb"){
                                        CMasFebPreEducation cmfpe=new CMasFebPreEducation(fac);
                                        cmfpe.setVisible(true);
                                    }
                                    else if(value2=="July"){
                                        CMasJulyPreEducation cmjpe=new CMasJulyPreEducation(fac);
                                        cmjpe.setVisible(true);
                                    }
                                }catch(Exception e){
                                    JOptionPane.showMessageDialog(null, e);
                                }
                            }
                        }
                        else if(fac=="Engineering")
                        {
                            if(value1=="Bsc")
                            {
                                String Sql="INSERT INTO e_bac_student (fName,lName,dob,address,telNo,email,intake) values (?,?,?,?,?,?,?)";
                                try{
                                    pst=conn.prepareStatement(Sql);
                                    pst.setString(1,txtfName.getText());
                                    pst.setString(2,txtlName.getText());
                                    pst.setString(3,txtdob.getText());
                                    pst.setString(4,txtaddress.getText());
                                    pst.setString(5,txtemail.getText());
                                    pst.setString(6,txtemail.getText());

                                    pst.setString(7,value2);

                                    pst.executeUpdate();
                                    //if(rs.next()){
                                        if(value2=="Feb"){
                                            CBacFebPreEducation cbfpe=new CBacFebPreEducation(fac);
                                            cbfpe.setVisible(true);
                                        }
                                        else if(value2=="July"){
                                            CBacJulyPreEducation cbjpe=new CBacJulyPreEducation(fac);
                                            cbjpe.setVisible(true);
                                        }

                                    }catch(Exception e){
                                        JOptionPane.showMessageDialog(null, e);
                                    }
                                }

                                else if(value1=="Msc")
                                {
                                    String Sql="INSERT INTO e_mas_student (fName,lName,dob,address,telNo,email,intake) values (?,?,?,?,?,?,?)";
                                    try{
                                        pst=conn.prepareStatement(Sql);
                                        pst.setString(1,txtfName.getText());
                                        pst.setString(2,txtlName.getText());
                                        pst.setString(3,txtdob.getText());
                                        pst.setString(4,txtaddress.getText());
                                        pst.setString(5,txtemail.getText());
                                        pst.setString(6,txtemail.getText());

                                        pst.setString(7,value2);

                                        pst.executeUpdate();
                                        //if(rs.next()){

                                            if(value2=="Feb"){
                                                CMasFebPreEducation cmfpe=new CMasFebPreEducation(fac);
                                                cmfpe.setVisible(true);
                                            }
                                            else if(value2=="July"){
                                                CMasJulyPreEducation cmjpe=new CMasJulyPreEducation(fac);
                                                cmjpe.setVisible(true);
                                            }
                                        }catch(Exception e){
                                            JOptionPane.showMessageDialog(null, e);
                                        }
                                    }
                                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CHome h=new CHome();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdobActionPerformed

    private void txtlNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlNameActionPerformed

    private void txtfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNameActionPerformed

    private void txttelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_faculty;
    private javax.swing.JComboBox<String> combo_intake;
    private javax.swing.JComboBox<String> combo_type;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel fName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lName;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfName;
    private javax.swing.JTextField txtlName;
    private javax.swing.JTextField txttelNo;
    // End of variables declaration//GEN-END:variables
}
