/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

/**
 *
 * @author Rangoda
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

public class AddTeacher extends javax.swing.JFrame {

    /**
     * Creates new form AddTeacher
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public AddTeacher() {
        initComponents();
        
        setSize(576,610);
        setResizable(false);
        
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        combo_tType = new javax.swing.JComboBox<>();
        txttecID = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txttitle = new javax.swing.JTextField();
        txtqualification = new javax.swing.JTextField();
        txtsubjects = new javax.swing.JTextField();
        txtlabID = new javax.swing.JTextField();
        txtroom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Add Teacher");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(253, 38, 113, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Type:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(101, 101, 36, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Teacher ID:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(101, 173, 72, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(101, 222, 40, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Qualifications:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(101, 324, 83, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Title:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(101, 274, 29, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Subjects:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(101, 373, 58, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Room:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(101, 422, 42, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Lab ID:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(101, 469, 45, 17);

        combo_tType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_tType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecturer", "Instructor" }));
        jPanel1.add(combo_tType);
        combo_tType.setBounds(293, 98, 89, 23);
        jPanel1.add(txttecID);
        txttecID.setBounds(293, 173, 121, 20);
        jPanel1.add(txtname);
        txtname.setBounds(293, 222, 121, 20);
        jPanel1.add(txttitle);
        txttitle.setBounds(293, 274, 121, 20);
        jPanel1.add(txtqualification);
        txtqualification.setBounds(293, 324, 121, 20);
        jPanel1.add(txtsubjects);
        txtsubjects.setBounds(293, 373, 121, 20);

        txtlabID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlabIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtlabID);
        txtlabID.setBounds(293, 469, 123, 20);
        jPanel1.add(txtroom);
        txtroom.setBounds(293, 422, 121, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(418, 527, 69, 25);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsbm/images/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 11, 57, 33);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsbm/images/wallpaper4.jpg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 580, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            conn=MySqlConnect.ConnectDB();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        String Sql="INSERT INTO c_teacher (tecID,name,title,qualification,tType,subjects,room,labID) values (?,?,?,?,?,?,?,?)";
        try{
            String value=combo_tType.getSelectedItem().toString();
            
            //if(value=="Lecturer")
            //{
                //txtlabID.setEditable(false);
                
//                pst=conn.prepareStatement(Sql);
//                pst.setString(1,txttecID.getText());
//                pst.setString(2,txtname.getText());
//                pst.setString(3,txttitle.getText());
//                pst.setString(4,txtqualification.getText());
//                pst.setString(5,value);
//                pst.setString(6,txtsubjects.getText());
//                pst.setString(7,txtroom.getText());
            //}
            //else
            //{
                pst=conn.prepareStatement(Sql);
                pst.setString(1,txttecID.getText());
                pst.setString(2,txtname.getText());
                pst.setString(3,txttitle.getText());
                pst.setString(4,txtqualification.getText());
                pst.setString(5,value);
                pst.setString(6,txtsubjects.getText());
                pst.setString(7,txtroom.getText());
                pst.setString(8,txtlabID.getText());
            //}
                
            
            
            
            
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Record added successfully");
            CHome h=new CHome();
            h.setVisible(true);
            dispose();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CHome h=new CHome();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtlabIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlabIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlabIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_tType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtlabID;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtqualification;
    private javax.swing.JTextField txtroom;
    private javax.swing.JTextField txtsubjects;
    private javax.swing.JTextField txttecID;
    private javax.swing.JTextField txttitle;
    // End of variables declaration//GEN-END:variables
}
