/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

/**
 *
 * @author Rangoda
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

public class CBacFebEnroll extends javax.swing.JFrame {

    /**
     * Creates new form CBacFebEnroll
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public CBacFebEnroll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtregNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sub11 = new javax.swing.JComboBox<>();
        sub12 = new javax.swing.JComboBox<>();
        sub21 = new javax.swing.JComboBox<>();
        sub22 = new javax.swing.JComboBox<>();
        sub13 = new javax.swing.JComboBox<>();
        sub14 = new javax.swing.JComboBox<>();
        sub23 = new javax.swing.JComboBox<>();
        sub24 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enroll Details");

        jLabel2.setText("Registration number:");

        txtregNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregNoActionPerformed(evt);
            }
        });

        jLabel3.setText("Basket Subjects:");

        jLabel4.setText("Sem 1:");

        jLabel5.setText("Sem 2:");

        sub11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Web", "Latex" }));

        sub12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Python", "Scala" }));

        sub21.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Media", "Graphics" }));

        sub22.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java", "C#" }));

        sub13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maths1", "Stat" }));

        sub14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Econ", "BS" }));

        sub23.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Discrete", "Logarithms" }));

        sub24.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accounting", "Management" }));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(78, 78, 78)
                                .addComponent(txtregNo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(59, 59, 59))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sub11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sub12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(sub21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sub24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sub22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtregNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtregNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregNoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            conn=MySqlConnect.ConnectDB();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        String Sql1="UPDATE c_bac_student SET regNo=? where sID=(Select max(sID) as sID from c_bac_student)";
        
        try{
            pst=conn.prepareStatement(Sql1);
            pst.setString(1,txtregNo.getText());
            
            pst.executeUpdate();
//            if(true){
//                CBacFebEnroll cbfe=new CBacFebEnroll();
//                cbfe.setVisible(true);
//            }
//            else{
//                JOptionPane.showMessageDialog(null, "Invalid username or password","Access Denied", JOptionPane.ERROR_MESSAGE);
//            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
//        String value1=sub11.getSelectedItem().toString();
//        String value2=sub12.getSelectedItem().toString();
//        String value3=sub13.getSelectedItem().toString();
//        String value4=sub14.getSelectedItem().toString();
//        String value5=sub21.getSelectedItem().toString();
//        String value6=sub22.getSelectedItem().toString();
//        String value7=sub23.getSelectedItem().toString();
//        String value8=sub24.getSelectedItem().toString();
        
        String[] values={sub11.getSelectedItem().toString(),sub12.getSelectedItem().toString(),
                        sub13.getSelectedItem().toString(),sub14.getSelectedItem().toString(),
                        sub21.getSelectedItem().toString(),sub22.getSelectedItem().toString(),
                        sub23.getSelectedItem().toString(),sub24.getSelectedItem().toString()};
        
        
        
        for(int i=0; i<8; i++)
        {
            //String Sql2="INSERT INTO student_subject (regNo,subject) values(?,?)";
            
//            String Sql2="SELECT id FROM c_subject WHERE name=values[i]";
//            try {
//                pst=conn.prepareStatement(Sql2);
//            } catch (SQLException ex) {
//                Logger.getLogger(CBacFebEnroll.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            try {
//                rs=pst.executeQuery();
//            } catch (SQLException ex) {
//                Logger.getLogger(CBacFebEnroll.class.getName()).log(Level.SEVERE, null, ex);
//            }
            
//            String Sql2="INSERT INTO c_bac_student_subject (sID, id) \n" +
//                        "SELECT c_bac_student.sID, c_subject.id \n" +
//                        "FROM c_bac_student, c_subject \n" +
//                        "WHERE c_bac_student.regNo='txtregNo.getText()' \n" +
//                        "AND c_subject.name='values[i]'";
            
//            String Sql2="INSERT INTO c_bac_student_subject (sID, id) SELECT c_bac_student.sID, c_subject.id FROM c_bac_student, c_subject WHERE c_bac_student.regNo='txtregNo.getText().toString()' AND c_subject.name='values[i]'";
            
            String val1=txtregNo.getText().toString();
            String val2=values[i];
            
            String x="select sID from c_bac_student where regNo='"+val1+"'";
            try {
                pst=conn.prepareStatement(x);
            } catch (SQLException ex) {
                Logger.getLogger(CBacFebEnroll.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                //pst.setString(1,txtregNo.getText());
                rs=pst.executeQuery();
            } catch (SQLException ex) {
                Logger.getLogger(CBacFebEnroll.class.getName()).log(Level.SEVERE, null, ex);
            }
            int season1 = 0;
            try {
                if(rs.next())
                    season1 = rs.getInt(1);
            } catch (SQLException ex) {
                Logger.getLogger(CBacFebEnroll.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            String y="select id from c_subject where name='"+val2+"'";
            try {
                pst=conn.prepareStatement(y);
            } catch (SQLException ex) {
                Logger.getLogger(CBacFebEnroll.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                //pst.setString(1,txtregNo.getText());
                rs=pst.executeQuery();
            } catch (SQLException ex) {
                Logger.getLogger(CBacFebEnroll.class.getName()).log(Level.SEVERE, null, ex);
            }
            int season2=0;
            try {
                if(rs.next())
                    season2 = rs.getInt(1);
            } catch (SQLException ex) {
                Logger.getLogger(CBacFebEnroll.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            String Sql2="insert into c_bac_student_subject (sID,id) values("+season1+", "+season2+")";
//                        "select a.sID,b.id \n" +
//                        "from c_bac_student a,c_subject b \n" +
//                        "where a.regNo = '$val1' \n" +
//                        "and b.name = '$values[i]'";
            try{
            pst=conn.prepareStatement(Sql2);
            //pst.setString(1,txtregNo.getText());
            //pst.setString(2,rs.getString(1));
            
            //rs=pst.executeQuery();
            pst.executeUpdate();
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        PaymentDetails pd=new PaymentDetails();
        pd.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CBacFebEnroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CBacFebEnroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CBacFebEnroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CBacFebEnroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CBacFebEnroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> sub11;
    private javax.swing.JComboBox<String> sub12;
    private javax.swing.JComboBox<String> sub13;
    private javax.swing.JComboBox<String> sub14;
    private javax.swing.JComboBox<String> sub21;
    private javax.swing.JComboBox<String> sub22;
    private javax.swing.JComboBox<String> sub23;
    private javax.swing.JComboBox<String> sub24;
    private javax.swing.JTextField txtregNo;
    // End of variables declaration//GEN-END:variables
}
