/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

/**
 *
 * @author Rangoda
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

public class CMasFebPreEducation extends javax.swing.JFrame {

    /**
     * Creates new form CMasFebPreEducation
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    String fac;
    
    public CMasFebPreEducation() {
        initComponents();
    }
    
    public CMasFebPreEducation(String para){
        initComponents();
        this.fac=para;
        
        setSize(576,610);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtqType = new javax.swing.JTextField();
        txtinstitute = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtyearComp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtgpa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Previous Education");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(213, 33, 173, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Qualification type:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(93, 111, 109, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Institute:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(93, 182, 55, 17);

        txtqType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtqType);
        txtqType.setBounds(265, 108, 153, 23);

        txtinstitute.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtinstitute);
        txtinstitute.setBounds(265, 179, 153, 23);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Year of completion:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(93, 254, 119, 17);

        txtyearComp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtyearComp);
        txtyearComp.setBounds(265, 251, 153, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("GPA:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(93, 320, 30, 17);

        txtgpa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtgpa);
        txtgpa.setBounds(265, 317, 153, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(369, 404, 76, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsbm/images/wallpaper4.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 580, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            conn=MySqlConnect.ConnectDB();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(fac=="Computing")
        {
            String Sql="UPDATE c_mas_student SET qualificationType=? , institute=? , yearComp=?, gpa=? WHERE sID=(SELECT MAX(sID) AS sID FROM c_mas_student)";
            try{
                pst=conn.prepareStatement(Sql);
                pst.setString(1,txtqType.getText());
                pst.setString(2,txtinstitute.getText());
                pst.setString(3,txtyearComp.getText());
                pst.setString(4,txtgpa.getText());
                pst.executeUpdate();
                if(true){
                    CMasFebEnroll cmfe=new CMasFebEnroll();
                    cmfe.setVisible(true);
                    //System.exit(0);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Invalid username or password","Access Denied", JOptionPane.ERROR_MESSAGE);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        else if(fac=="Business")
        {
            String Sql="UPDATE b_mas_student SET qualificationType=? , institute=? , yearComp=?, gpa=? WHERE sID=(SELECT MAX(sID) AS sID FROM b_mas_student)";
            try{
                pst=conn.prepareStatement(Sql);
                pst.setString(1,txtqType.getText());
                pst.setString(2,txtinstitute.getText());
                pst.setString(3,txtyearComp.getText());
                pst.setString(4,txtgpa.getText());
                pst.executeUpdate();
                if(true){
                    CMasFebEnroll cmfe=new CMasFebEnroll();
                    cmfe.setVisible(true);
                    //System.exit(0);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Invalid username or password","Access Denied", JOptionPane.ERROR_MESSAGE);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        if(fac=="Engineering")
        {
            String Sql="UPDATE e_mas_student SET qualificationType=? , institute=? , yearComp=?, gpa=? WHERE sID=(SELECT MAX(sID) AS sID FROM e_mas_student)";
            try{
                pst=conn.prepareStatement(Sql);
                pst.setString(1,txtqType.getText());
                pst.setString(2,txtinstitute.getText());
                pst.setString(3,txtyearComp.getText());
                pst.setString(4,txtgpa.getText());
                pst.executeUpdate();
                if(true){
                    CMasFebEnroll cmfe=new CMasFebEnroll();
                    cmfe.setVisible(true);
                    //System.exit(0);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Invalid username or password","Access Denied", JOptionPane.ERROR_MESSAGE);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CMasFebPreEducation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CMasFebPreEducation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CMasFebPreEducation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CMasFebPreEducation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CMasFebPreEducation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtgpa;
    private javax.swing.JTextField txtinstitute;
    private javax.swing.JTextField txtqType;
    private javax.swing.JTextField txtyearComp;
    // End of variables declaration//GEN-END:variables
}
