/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

/**
 *
 * @author Rangoda
 */

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

public class PaymentDetails extends javax.swing.JFrame {

    /**
     * Creates new form PaymentDetails
     */
    
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    static String[] values;
    static String fac;
    
    public PaymentDetails() {
        initComponents();
    }
    
    public PaymentDetails(String[] para1, String para2)
    {
        initComponents();
        this.values=para1;
        this.fac=para2;
        add();
        calculate();
        
        setSize(576,610);
        setResizable(false);
    }
    
    public void add()
    {
        try
        {          
            DefaultListModel dlm=new DefaultListModel();
            for(int i=0; i<values.length; i++)
            {
                //opt=opt+values[i]+"\n";
                //txtsubjects.setText(opt);
                dlm.addElement(values[i]);
            }
            listsubjects.setModel(dlm);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void calculate()
    {
        if(fac=="Computing")
        {
            try
            {
                conn=MySqlConnect.ConnectDB();
                double amount=0.0;
                String temp;

                for(int i=0; i<4; i++)
                {

                    //System.out.println("aaa");
                    String q="select * from c_subject where name='"+values[i]+"'";
                    pst=conn.prepareStatement(q);
                    rs=pst.executeQuery();
                    //System.out.println("aaa");
                    //System.out.println(rs.getString("price"));

                    if(rs.next())
                    {
                        temp=rs.getString("price");
                        amount=amount+Double.parseDouble(temp);
                        //System.out.println(amount);
                    }

                }
                //System.out.println(amount);
                txtpay.setText(String.valueOf(amount));

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        
        if(fac=="Business")
        {
            try
            {
                conn=MySqlConnect.ConnectDB();
                double amount=0.0;
                String temp;

                for(int i=0; i<4; i++)
                {

                    //System.out.println("aaa");
                    String q="select * from b_subject where name='"+values[i]+"'";
                    pst=conn.prepareStatement(q);
                    rs=pst.executeQuery();
                    //System.out.println("aaa");
                    //System.out.println(rs.getString("price"));

                    if(rs.next())
                    {
                        temp=rs.getString("price");
                        amount=amount+Double.parseDouble(temp);
                        //System.out.println(amount);
                    }

                }
                //System.out.println(amount);
                txtpay.setText(String.valueOf(amount));

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        if(fac=="Engineering")
        {
            try
            {
                conn=MySqlConnect.ConnectDB();
                double amount=0.0;
                String temp;

                for(int i=0; i<4; i++)
                {

                    //System.out.println("aaa");
                    String q="select * from e_subject where name='"+values[i]+"'";
                    pst=conn.prepareStatement(q);
                    rs=pst.executeQuery();
                    //System.out.println("aaa");
                    //System.out.println(rs.getString("price"));

                    if(rs.next())
                    {
                        temp=rs.getString("price");
                        amount=amount+Double.parseDouble(temp);
                        //System.out.println(amount);
                    }

                }
                //System.out.println(amount);
                txtpay.setText(String.valueOf(amount));

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listsubjects = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Payment Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(215, 26, 147, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Subjects:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(71, 107, 56, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Payment:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(71, 327, 59, 17);

        txtpay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtpay);
        txtpay.setBounds(214, 323, 113, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(366, 451, 65, 25);

        listsubjects.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(listsubjects);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(215, 107, 216, 161);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Rs.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(191, 326, 19, 17);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsbm/images/wallpaper4.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 580, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CHome h=new CHome();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentDetails(values, fac).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listsubjects;
    private javax.swing.JTextField txtpay;
    // End of variables declaration//GEN-END:variables
}
